
import { EmergencyDrug, SearchEngine, ClinicalScale } from './types';

export const MEDICAL_BLUE = '#0EA5E9';

export const SEARCH_ENGINES: SearchEngine[] = [
  { name: '丁香园用药助手', url: 'https://drugs.dxy.cn/pc/search?keyword=', icon: 'D' },
  { name: '百度医典/百科', url: 'https://baike.baidu.com/item/', icon: 'B' },
  { name: '百度搜索', url: 'https://www.baidu.com/s?wd=', icon: '百度' },
  { name: '必应 Bing', url: 'https://www.bing.com/search?q=', icon: '必应' },
  { name: 'DuckDuckGo', url: 'https://duckduckgo.com/?q=', icon: 'DDG' },
  { name: '豆包 AI', url: 'https://www.doubao.com/search?q=', icon: 'D' }
];

export const RENAL_STAGES = [
  { stage: 'G1', range: '≥ 90', desc: '肾功能正常', color: 'bg-[#00B17D]', detail: '正常或高 eGFR。' },
  { stage: 'G2', range: '60-89', desc: '轻度下降', color: 'bg-[#9CD100]', detail: 'eGFR 轻度降低。' },
  { stage: 'G3a', range: '45-59', desc: '中度下降', color: 'bg-[#F2B01B]', detail: '中度 eGFR 降低。' },
  { stage: 'G3b', range: '30-44', desc: '中重度下降', color: 'bg-[#F97316]', detail: '中重度 eGFR 降低。' },
  { stage: 'G4', range: '15-29', desc: '重度下降', color: 'bg-[#EF4444]', detail: '重度 eGFR 降低。' },
  { stage: 'G5', range: '< 15', desc: '肾衰竭', color: 'bg-[#1E293B]', detail: '尿毒症期。' },
];

export const CLINICAL_SCALES: ClinicalScale[] = [
  {
    id: 'gcs',
    name: 'GCS 昏迷评分',
    dept: '神经/急诊',
    description: '格拉斯哥昏迷评分法，评估意识障碍程度。',
    items: [
      { label: '睁眼反应 (E)', options: [{label: '自动睁眼', score: 4}, {label: '呼唤睁眼', score: 3}, {label: '刺痛睁眼', score: 2}, {label: '不睁眼', score: 1}] },
      { label: '语言反应 (V)', options: [{label: '回答正确', score: 5}, {label: '回答错误', score: 4}, {label: '含糊不清', score: 3}, {label: '唯有发音', score: 2}, {label: '无言语', score: 1}] },
      { label: '肢体运动 (M)', options: [{label: '遵嘱动作', score: 6}, {label: '刺痛定位', score: 5}, {label: '刺痛避让', score: 4}, {label: '刺痛屈曲', score: 3}, {label: '刺痛伸展', score: 2}, {label: '无运动', score: 1}] }
    ],
    interpretation: (t) => t >= 13 ? '轻度意识障碍' : (t >= 9 ? '中度意识障碍' : '重度意识障碍 (昏迷)')
  },
  {
    id: 'nrs2002',
    name: 'NRS-2002 营养风险筛查',
    dept: '普内/外科',
    description: '用于住院患者营养风险筛查。',
    items: [
      { label: '营养状况受损', options: [{label: '正常', score: 0}, {label: '轻度(3个月下5%)', score: 1}, {label: '中度(2个月下5%)', score: 2}, {label: '重度(1个月下5%)', score: 3}] },
      { label: '疾病严重程度', options: [{label: '无', score: 0}, {label: '轻度(如骨折)', score: 1}, {label: '中度(如重大手术)', score: 2}, {label: '重度(如ICU患者)', score: 3}] },
      { label: '年龄≥70岁', options: [{label: '否', score: 0}, {label: '是', score: 1}] }
    ],
    interpretation: (t) => t >= 3 ? '存在营养风险' : '暂无营养风险'
  }
];

export const EMERGENCY_DRUGS: EmergencyDrug[] = [
  { name: '1. 去甲肾上腺素', spec: '2mg:1ml', defaultAmount: 4, amountUnit: 'mg', defaultVolume: 50, defaultSpeed: 4.5, range: '0.1ug/kg/min (0.1-2)', indications: '休克，尤其是感染性休克', solvent: 'NS', isWeightDependent: true, targetDoseUnit: 'ug/kg/min' },
  { name: '2. 美托洛尔', spec: '5mg:5ml', defaultAmount: 20, amountUnit: 'mg', defaultVolume: 35, defaultSpeed: 2, range: '0.8mg/h, 固定走速', indications: '快速性心律失常', solvent: 'NS', isWeightDependent: false, targetDoseUnit: 'mg/h' },
  { name: '3. 咪达唑仑 (力月西)', spec: '50mg:10ml', defaultAmount: 50, amountUnit: 'mg', defaultVolume: 50, defaultSpeed: 4, range: '0.066mg/kg/h (0.04-0.2)', indications: '镇静', solvent: 'NS', isWeightDependent: true, targetDoseUnit: 'mg/kg/h' },
  { name: '4. 瑞芬太尼 (锐纷)', spec: '2mg', defaultAmount: 4, amountUnit: 'mg', defaultVolume: 50, defaultSpeed: 4, range: '0.088ug/kg/min (0.05-0.2)', indications: '镇痛', solvent: 'NS', isWeightDependent: true, targetDoseUnit: 'ug/kg/min' },
  { name: '5. 比阿培南 (安信)', spec: '0.3g', defaultAmount: 0.6, amountUnit: 'g', defaultVolume: 50, defaultSpeed: 17, range: '200mg/h, 固定走速', indications: '抗感染', solvent: 'NS', isWeightDependent: false, targetDoseUnit: 'mg/h' },
  { name: '6. 尼可地尔 (瑞科喜)', spec: '12mg', defaultAmount: 36, amountUnit: 'mg', defaultVolume: 50, defaultSpeed: 4, range: '2.88mg/h (2-6)', indications: '不稳定型心绞痛', solvent: 'NS/GS', isWeightDependent: false, targetDoseUnit: 'mg/h' },
  { name: '7. 氢化可的松', spec: '25mg:5ml', defaultAmount: 200, amountUnit: 'mg', defaultVolume: 10, defaultSpeed: 2, range: '8mg/h, 固定走速', indications: '感染性休克', solvent: 'GS', isWeightDependent: false, targetDoseUnit: 'mg/h' },
  { name: '8. 重组人脑利钠肽', spec: '0.5mg', defaultAmount: 1, amountUnit: 'mg', defaultVolume: 50, defaultSpeed: 1.35, range: '0.0075ug/kg/min', indications: '抗心衰', solvent: 'NS/GS', isWeightDependent: true, targetDoseUnit: 'ug/kg/min' },
  { name: '9. 左西孟旦 (悦文)', spec: '12.5mg:5ml', defaultAmount: 12.5, amountUnit: 'mg', defaultVolume: 50, defaultSpeed: 2.1, range: '0.1458ug/kg/min', indications: '抗心衰', solvent: 'GS', isWeightDependent: true, targetDoseUnit: 'ug/kg/min' },
  { name: '10. 右美托咪定', spec: '0.2mg:2ml', defaultAmount: 0.2, amountUnit: 'mg', defaultVolume: 50, defaultSpeed: 5, range: '0.33ug/kg/min (0.1-0.7)', indications: '镇静', solvent: 'NS', isWeightDependent: true, targetDoseUnit: 'ug/kg/min' },
  { name: '11. 生长抑素', spec: '3mg', defaultAmount: 3, amountUnit: 'mg', defaultVolume: 50, defaultSpeed: 4.16, range: '0.25mg/h, 固定走速', indications: '消化道出血', solvent: 'NS', isWeightDependent: false, targetDoseUnit: 'mg/h' },
  { name: '12. 硝酸甘油', spec: '5mg:1ml', defaultAmount: 5, amountUnit: 'mg', defaultVolume: 50, defaultSpeed: 3, range: '5ug/min (5-200)', indications: '降压', solvent: 'NS', isWeightDependent: false, targetDoseUnit: 'ug/min' },
  { name: '13. 硝普钠', spec: '50mg', defaultAmount: 50, amountUnit: 'mg', defaultVolume: 50, defaultSpeed: 1.8, range: '0.5ug/kg/min (0.5-6)', indications: '降压', solvent: 'NS', isWeightDependent: true, targetDoseUnit: 'ug/kg/min' },
  { name: '14. 多巴胺', spec: '20mg:2ml', defaultAmount: 180, amountUnit: 'mg', defaultVolume: 40, defaultSpeed: 1, range: '1ug/kg/min (1-15)', indications: '利尿、强心、升压', solvent: 'NS', isWeightDependent: true, targetDoseUnit: 'ug/kg/min' },
  { name: '15. 多巴酚丁胺', spec: '20mg:2ml', defaultAmount: 180, amountUnit: 'mg', defaultVolume: 40, defaultSpeed: 2.5, range: '2.5ug/kg/min (2.5-15)', indications: '强心升压', solvent: 'NS/GS', isWeightDependent: true, targetDoseUnit: 'ug/kg/min' },
  { name: '16. 托拉塞米', spec: '20mg', defaultAmount: 20, amountUnit: 'mg', defaultVolume: 20, defaultSpeed: 4, range: '4mg/h 或 8mg/h', indications: '利尿、心衰', solvent: 'NS', isWeightDependent: false, targetDoseUnit: 'mg/h' },
  { name: '17. 利尿合剂', spec: '多合一', defaultAmount: 50, amountUnit: 'mg', defaultVolume: 50, defaultSpeed: 3.5, range: '维持出入平衡', indications: '利尿改善心功能', solvent: 'NS', isWeightDependent: false, targetDoseUnit: 'ml/h' },
  { name: '18. 氯化钾', spec: '1g:1ml', defaultAmount: 3, amountUnit: 'g', defaultVolume: 50, defaultSpeed: 5, range: '0.3g/h (0.3-0.75)', indications: '补钾', solvent: 'NS', isWeightDependent: false, targetDoseUnit: 'mg/h' },
  { name: '19. 钾镁合剂', spec: '多合一', defaultAmount: 5.5, amountUnit: 'g', defaultVolume: 50, defaultSpeed: 5, range: '纠正缺钾缺镁', indications: '电解质紊乱', solvent: 'NS', isWeightDependent: false, targetDoseUnit: 'ml/h' },
  { name: '20. 丙戊酸钠 (德巴金)', spec: '0.4g', defaultAmount: 0.4, amountUnit: 'g', defaultVolume: 50, defaultSpeed: 5, range: '0.666mg/kg/h', indications: '癫痫发作', solvent: 'NS', isWeightDependent: true, targetDoseUnit: 'mg/kg/h' },
  { name: '21. 垂体后叶素', spec: '6U:1ml', defaultAmount: 12, amountUnit: 'U', defaultVolume: 50, defaultSpeed: 3, range: '0.012U/min (0.012-0.2)', indications: '大咯血', solvent: 'NS', isWeightDependent: false, targetDoseUnit: 'U/min' },
  { name: '22. 妥拉唑林', spec: '10mg:1ml', defaultAmount: 50, amountUnit: 'mg', defaultVolume: 50, defaultSpeed: 2, range: '2mg/h, 固定走速', indications: '大咯血、心衰', solvent: 'NS', isWeightDependent: false, targetDoseUnit: 'mg/h' },
  { name: '23. 奥曲肽 (善宁)', spec: '0.1mg:1ml', defaultAmount: 0.6, amountUnit: 'mg', defaultVolume: 50, defaultSpeed: 4.167, range: '0.05mg/h, 固定走速', indications: '消化道出血', solvent: 'NS', isWeightDependent: false, targetDoseUnit: 'mg/h' },
  { name: '24. 胺碘酮 (可达龙)', spec: '150mg:3ml', defaultAmount: 150, amountUnit: 'mg', defaultVolume: 20, defaultSpeed: 2, range: '1mg/min (首6h)', indications: '快速心律失常', solvent: 'GS', isWeightDependent: false, targetDoseUnit: 'mg/h' },
  { name: '25. 艾司洛尔 (爱倍)', spec: '200mg:2ml', defaultAmount: 1000, amountUnit: 'mg', defaultVolume: 50, defaultSpeed: 2, range: '0.011mg/kg/min', indications: '快速心律失常', solvent: 'NS/GS', isWeightDependent: true, targetDoseUnit: 'mg/kg/h' },
  { name: '26. 异丙肾上腺素', spec: '1mg:2ml', defaultAmount: 1, amountUnit: 'mg', defaultVolume: 50, defaultSpeed: 3, range: '1ug/min', indications: '缓慢心律失常', solvent: 'NS', isWeightDependent: false, targetDoseUnit: 'ug/min' },
  { name: '27. 去氧肾上腺素', spec: '10mg:1ml', defaultAmount: 10, amountUnit: 'mg', defaultVolume: 50, defaultSpeed: 12, range: '40ug/min (40-180)', indications: '治疗休克低血压', solvent: 'NS', isWeightDependent: false, targetDoseUnit: 'ug/min' },
  { name: '28. 肾上腺素 (付肾)', spec: '1mg:1ml', defaultAmount: 3, amountUnit: 'mg', defaultVolume: 50, defaultSpeed: 6, range: '0.1ug/kg/min (0.1-2.0)', indications: '心源性休克', solvent: 'NS', isWeightDependent: true, targetDoseUnit: 'ug/kg/min' },
  { name: '29. 尼莫地平', spec: '10mg:50ml', defaultAmount: 10, amountUnit: 'mg', defaultVolume: 50, defaultSpeed: 5, range: '1mg/h (1-2)', indications: '蛛网膜下腔出血', solvent: '原液', isWeightDependent: false, targetDoseUnit: 'mg/h' },
  { name: '30. 尼卡地平', spec: '10mg:10ml', defaultAmount: 30, amountUnit: 'mg', defaultVolume: 30, defaultSpeed: 3, range: '0.5ug/kg/min', indications: '高血压急症', solvent: 'NS', isWeightDependent: true, targetDoseUnit: 'ug/kg/min' },
  { name: '31. 单硝酸异山梨酯', spec: '10mg:1ml', defaultAmount: 20, amountUnit: 'mg', defaultVolume: 50, defaultSpeed: 9, range: '3.6mg/h (3.6-7.2)', indications: '心绞痛', solvent: 'NS', isWeightDependent: false, targetDoseUnit: 'mg/h' },
  { name: '32. 硝酸异山梨酯', spec: '10mg:10ml', defaultAmount: 20, amountUnit: 'mg', defaultVolume: 40, defaultSpeed: 2.5, range: '1mg/h (1-10)', indications: '急性心梗、心衰', solvent: 'NS', isWeightDependent: false, targetDoseUnit: 'mg/h' },
  { name: '33. 乌拉地尔 (亚宁定)', spec: '25mg:5ml', defaultAmount: 100, amountUnit: 'mg', defaultVolume: 50, defaultSpeed: 4.5, range: '9mg/h (9-24)', indications: '高血压急症', solvent: 'NS', isWeightDependent: false, targetDoseUnit: 'mg/h' },
  { name: '34. 利多卡因', spec: '0.1g:5ml', defaultAmount: 200, amountUnit: 'mg', defaultVolume: 50, defaultSpeed: 15, range: '1mg/min (1-3)', indications: '室性心律失常', solvent: 'NS', isWeightDependent: false, targetDoseUnit: 'mg/h' },
  { name: '35. 地尔硫卓 (合贝爽)', spec: '50mg', defaultAmount: 50, amountUnit: 'mg', defaultVolume: 50, defaultSpeed: 3.6, range: '1ug/kg/min (1-5)', indications: '不稳定心绞痛', solvent: 'NS', isWeightDependent: true, targetDoseUnit: 'ug/kg/min' },
  { name: '36. 地尔硫卓 (高压版)', spec: '50mg', defaultAmount: 50, amountUnit: 'mg', defaultVolume: 50, defaultSpeed: 18, range: '5ug/kg/min (5-15)', indications: '高血压急症', solvent: 'NS', isWeightDependent: true, targetDoseUnit: 'ug/kg/min' },
  { name: '37. 肝素钠', spec: '12500U:2ml', defaultAmount: 12500, amountUnit: 'U', defaultVolume: 50, defaultSpeed: 2, range: '500U/h', indications: '抗凝、预防血栓形成', solvent: 'NS', isWeightDependent: false, targetDoseUnit: 'U/h' },
  { name: '38. 奥普力农', spec: '5mg:5ml', defaultAmount: 15, amountUnit: 'mg', defaultVolume: 50, defaultSpeed: 2.1, range: '0.175ug/kg/min', indications: '急性心衰', solvent: 'NS/GS', isWeightDependent: true, targetDoseUnit: 'ug/kg/min' },
  { name: '39. 地西泮 (安定)', spec: '10mg:2ml', defaultAmount: 10, amountUnit: 'mg', defaultVolume: 2, defaultSpeed: 1, range: '5mg/h (5-10)', indications: '抗惊厥、镇静', solvent: '原液', isWeightDependent: false, targetDoseUnit: 'mg/h' },
  { name: '40. 吗啡', spec: '10mg:1ml', defaultAmount: 50, amountUnit: 'mg', defaultVolume: 50, defaultSpeed: 1, range: '1mg/h (1-6)', indications: '镇痛、镇静', solvent: 'NS', isWeightDependent: false, targetDoseUnit: 'mg/h' },
  { name: '41. 丙泊酚 (得普利麻)', spec: '200mg:20ml', defaultAmount: 400, amountUnit: 'mg', defaultVolume: 50, defaultSpeed: 2.25, range: '0.3mg/kg/h', indications: '镇静', solvent: 'NS', isWeightDependent: true, targetDoseUnit: 'mg/kg/h' },
  { name: '42. 芬太尼', spec: '0.1mg:2ml', defaultAmount: 200, amountUnit: 'ug', defaultVolume: 50, defaultSpeed: 7.5, range: '0.5ug/kg/h', indications: '镇痛', solvent: 'NS', isWeightDependent: true, targetDoseUnit: 'ug/kg/h' },
  { name: '43. 冬眠合剂', spec: '多合一', defaultAmount: 100, amountUnit: 'mg', defaultVolume: 50, defaultSpeed: 1.2, range: '中枢镇静', indications: '中枢性高热', solvent: 'NS', isWeightDependent: false, targetDoseUnit: 'ml/h' },
  { name: '44. 氟马西尼', spec: '1mg:10ml', defaultAmount: 2, amountUnit: 'mg', defaultVolume: 30, defaultSpeed: 2.5, range: '0.1mg/h', indications: '逆转苯二氮卓', solvent: 'NS', isWeightDependent: false, targetDoseUnit: 'mg/h' },
  { name: '45. 维库溴铵', spec: '4mg', defaultAmount: 40, amountUnit: 'mg', defaultVolume: 50, defaultSpeed: 3.6, range: '0.8ug/kg/min', indications: '肌松药', solvent: 'NS', isWeightDependent: true, targetDoseUnit: 'ug/kg/min' },
  { name: '46. 顺阿曲库铵', spec: '10mg:5ml', defaultAmount: 100, amountUnit: 'mg', defaultVolume: 10, defaultSpeed: 5.4, range: '3ug/kg/min', indications: '肌松药', solvent: '原液', isWeightDependent: true, targetDoseUnit: 'ug/kg/min' },
  { name: '47. 布托啡诺', spec: '1mg:1ml', defaultAmount: 4, amountUnit: 'mg', defaultVolume: 50, defaultSpeed: 5, range: '0.4mg/h', indications: '镇痛', solvent: 'NS', isWeightDependent: false, targetDoseUnit: 'mg/h' },
  { name: '48. 泮托拉唑 (洛赛克)', spec: '40mg', defaultAmount: 80, amountUnit: 'mg', defaultVolume: 50, defaultSpeed: 5, range: '8mg/h', indications: '护胃抑酸', solvent: 'NS', isWeightDependent: false, targetDoseUnit: 'mg/h' },
  { name: '49. 呋塞米 (速速)', spec: '20mg:2ml', defaultAmount: 40, amountUnit: 'mg', defaultVolume: 20, defaultSpeed: 5, range: '10mg/h (10-40)', indications: '利尿消肿', solvent: 'NS', isWeightDependent: false, targetDoseUnit: 'mg/h' },
  { name: '50. 氨茶碱', spec: '0.25g:2ml', defaultAmount: 500, amountUnit: 'mg', defaultVolume: 50, defaultSpeed: 2, range: '20mg/h', indications: '支气管哮喘', solvent: 'GS', isWeightDependent: false, targetDoseUnit: 'mg/h' },
  { name: '51. 胰岛素', spec: '400U:10ml', defaultAmount: 50, amountUnit: 'U', defaultVolume: 50, defaultSpeed: 1, range: '1U/h', indications: '控制血糖', solvent: 'NS', isWeightDependent: false, targetDoseUnit: 'U/h' }
];

export const FULL_DRUG_DATABASE = [
  { id: '1', name: '重酒石酸去甲肾上腺素注射液(正肾)', spec: '2mg: 1ml', dose: '4mg(2支)', solvent: 'NS 48ml', speed: '4.5ml/h', range: '0.1ug/kg/min, 0.1-2', indications: '休克，尤其是感染性休克' },
  { id: '2', name: '酒石酸美托洛尔注射液', spec: '5mg: 5ml', dose: '20mg(4支)', solvent: 'NS 30ml', speed: '2ml/h', range: '0.8mg/h, 固定走速', indications: '快速性心律失常' },
  { id: '3', name: '咪达唑仑注射液(力月西)', spec: '50mg: 10ml', dose: '50mg(1支)', solvent: 'NS 40ml', speed: '4ml/h', range: '0.066mg/kg/h, 0.04-0.2', indications: '镇静' },
  { id: '4', name: '注射用盐酸瑞芬太尼(锐纷)', spec: '2mg', dose: '4mg(2支)', solvent: 'NS 50ml', speed: '4ml/h', range: '0.088ug/kg/min, 0.05-0.2', indications: '镇痛' },
  { id: '5', name: '注射用比阿培南(安信)', spec: '0.3g', dose: '0.6g', solvent: 'NS 50ml', speed: '17ml/h', range: '200mg/h, 固定走速', indications: '抗感染' },
  { id: '6', name: '注射用尼可地尔(瑞科喜)', spec: '12mg', dose: '36mg(3支)', solvent: 'NS或GS 50ml', speed: '4ml/h', range: '2.88mg/h, 2-6', indications: '不稳定型心绞痛' },
  { id: '7', name: '氢化可的松注射液', spec: '25mg: 5ml', dose: '200mg(8支)', solvent: 'GS 10ml', speed: '2ml/h', range: '8mg/h, 固定走速', indications: '感染性休克' },
  { id: '8', name: '注射用重组人脑利钠肽(新活素)', spec: '0.5mg', dose: '1mg(2支)', solvent: 'NS或GS 50ml', speed: '1.35ml/h', range: '0.0075ug/kg/min, 0.0075-0.001', indications: '抗心衰' },
  { id: '9', name: '左西孟旦注射液(悦文)', spec: '12.5mg: 5ml', dose: '12.5mg(1支)', solvent: 'GS 45ml', speed: '2.1ml/h', range: '0.1458ug/kg/min, 0.05-0.2', indications: '抗心衰' },
  { id: '10', name: '盐酸右美托咪定注射液(佑必妥)', spec: '0.2mg: 2ml', dose: '0.2mg(1支)', solvent: 'NS 48ml', speed: '5ml/h', range: '0.33ug/kg/h, 0.1-0.7', indications: '镇静' },
  { id: '11', name: '注射用生长抑素(乙酰已基)', spec: '3mg', dose: '3mg(1支)', solvent: 'NS 50ml', speed: '4.16ml/h', range: '0.25mg/h, 固定走速', indications: '消化道出血' },
  { id: '12', name: '硝酸甘油注射液', spec: '5mg: 1ml', dose: '5mg(1支)', solvent: 'NS 49ml', speed: '3ml/h', range: '5ug/min, 5-200', indications: '降压' },
  { id: '13', name: '注射用硝普钠', spec: '50mg', dose: '50mg(1支)', solvent: 'NS 50ml', speed: '1.8ml/h', range: '0.5ug/kg/min, 0.5-6', indications: '降压' },
  { id: '14', name: '盐酸多巴胺注射液', spec: '20mg: 2ml', dose: '180mg(9支)', solvent: 'NS 32ml', speed: '1ml/h', range: '1ug/kg/min, 1-15', indications: '<2, 利尿; 2-10, 强心升压; >10, 升压抗休克' },
  { id: '15', name: '盐酸多巴酚丁胺注射液', spec: '20mg: 2ml', dose: '180mg(9支)', solvent: 'NS或GS 32ml', speed: '2.5ml/h', range: '2.5ug/kg/min, 2.5-15', indications: '强心升压抗休克' },
  { id: '16', name: '注射用托拉塞米(泽通)', spec: '20mg', dose: '20mg或40mg(1支或2支)', solvent: 'NS 20ml(溶液量20ml)', speed: '4ml/h', range: '4mg/h或8mg/h, 固定走速', indications: '利尿消肿、改善心脏前负荷' },
  { id: '17', name: '利尿合剂: 多巴胺注射液20mg(1支, 规格20mg: 2ml) +硝酸甘油注射液30mg(6支, 规格5mg: 1ml) +注射用托拉塞米20mg或40mg(1支或2支, 规格20mg)。先上述多巴胺、硝酸甘油+NS 42ml, 3-5ml/h; 2h后上述托拉塞米+NS 20ml, 4.5ml/h (多巴胺、硝酸甘油继续泵入)。', spec: '', dose: '', solvent: '', speed: '', range: '', indications: '小剂量多巴胺扩张肾动脉，硝酸甘油扩张冠状动脉，后予托拉塞米利尿', isFullText: true },
  { id: '18', name: '氯化钾注射液', spec: '1g: 1ml', dose: '3g(3支)', solvent: 'NS 20ml(总溶液量20ml)', speed: '5ml/h', range: '0.3g/h, 0.3-0.75', indications: '补钾，注意走中心静脉' },
  { id: '19', name: '钾镁合剂：氯化钾注射液3g(3支，规格1g: 0.1ml) +硫酸镁注射液2.5g(1支，规格2.5g: 10ml)。上述氯化钾、硫酸镁+NS250ml, 25ml/h', spec: '', dose: '', solvent: '', speed: '', range: '', indications: '补钾补镁，纠正低镁血症引起的低钾血症，注意精密输液器泵入', isFullText: true },
  { id: '20', name: '注射用丙戊酸钠(德巴金)', spec: '0.4g', dose: '0.4g(1支)', solvent: 'NS 50ml', speed: '5ml/h', range: '0.666mg/kg/h, 固定走速', indications: '癫痫发作' },
  { id: '21', name: '垂体后叶注射液(蚌生)', spec: '6U: 1ml', dose: '12U(2支)', solvent: 'NS 48ml', speed: '3ml/h', range: '0.012U/min, 0.012-0.2', indications: '大咯血，静脉滴注用法为：垂体后叶素12U+NS 250ml' },
  { id: '22', name: '甲磺酸酚妥拉明注射液(立其丁)', spec: '10mg: 1ml', dose: '50mg(5支)', solvent: 'NS 45ml', speed: '2ml/h', range: '2mg/h, 固定走速', indications: '大咯血，静脉滴注用法为：酚妥拉明20mg+NS 250ml，持续4h(精密输液器泵入)' },
  { id: '23', name: '醋酸奥曲肽注射液(善宁)', spec: '0.1mg: 1ml', dose: '0.6mg(6支)', solvent: 'NS 44ml', speed: '4.167ml/h', range: '0.05mg/h, 固定走速', indications: '消化道出血' },
  { id: '24', name: '盐酸胺碘酮注射液(可达龙)', spec: '150mg: 3ml', dose: '150mg(1支)', solvent: 'GS 20ml', speed: '2ml/min', range: '静脉推注10min(即按顺时针15mg/min静推)', indications: '快速性心律失常' },
  { id: '步骤1', name: '', spec: '', dose: '', solvent: '', speed: '', range: '', indications: '' },
  { id: '步骤2', name: '', spec: '150mg: 3ml', dose: '300mg(2支)', solvent: 'GS 44ml', speed: '10ml/h', range: '前6h时1mg/min', indications: '快速性心律失常' },
  { id: '步骤3', name: '', spec: '150mg: 3ml', dose: '300mg(2支)', solvent: 'GS 44ml', speed: '5ml/h', range: '后18h时0.5mg/min', indications: '快速性心律失常' },
  { id: '25', name: '盐酸艾司洛尔注射液(爱倍)', spec: '200mg: 2ml', dose: '1000mg(5支)', solvent: 'NS或GS 40ml', speed: '2ml/h', range: '0.011mg/kg/min, 0.01-0.3', indications: '快速性心律失常' },
  { id: '26', name: '盐酸异丙肾上腺素注射液', spec: '1mg: 2ml', dose: '1mg(1支)', solvent: 'NS 48ml', speed: '3ml/h', range: '1ug/min, 固定走速', indications: '缓慢心律失常' },
  { id: '27', name: '盐酸去甲肾上腺素注射液', spec: '10mg: 1ml', dose: '10mg(1支)', solvent: 'NS 49ml', speed: '12ml/h', range: '40ug/min, 40-180', indications: '治疗休克及低血压' },
  { id: '28', name: '盐酸肾上腺素注射液(付肾)', spec: '1mg: 1ml', dose: '3mg(3支)', solvent: 'NS 47ml', speed: '6ml/h', range: '0.1ug/kg/min, 0.1-2.0', indications: '心源性休克、心脏骤停' },
  { id: '29', name: '尼莫地平注射液(尼膜同)', spec: '10mg: 50ml', dose: '10mg(1支)', solvent: 'NS 0ml', speed: '5ml/h', range: '1mg/h, 1-2', indications: '蛛网膜下腔出血后脑血管痉挛引起的缺血性神经损伤' },
  { id: '30', name: '盐酸尼卡地平注射液(佩尔)', spec: '10mg: 10ml', dose: '30mg(3支)', solvent: 'NS 20ml', speed: '3ml/h', range: '0.5ug/kg/min, 0.5-6', indications: '高血压急症' },
  { id: '31', name: '单硝酸异山梨酯注射液', spec: '10mg: 1ml', dose: '20mg(2支)', solvent: 'NS 48ml', speed: '9ml/h', range: '3.6mg/h, 3.6-7.2', indications: '心绞痛' },
  { id: '32', name: '硝酸异山梨酯注射液', spec: '10mg: 10ml', dose: '20mg(2支)', solvent: 'NS 30ml', speed: '2.5ml/h', range: '1mg/h, 1-10', indications: '不稳定型心绞痛、变异型心绞痛、急性心肌梗死、急性左心衰' },
  { id: '33', name: '盐酸乌拉地尔注射液(亚宁定)', spec: '25mg: 5ml', dose: '100mg(4支)', solvent: 'NS 30ml', speed: '4.5ml/h', range: '9mg/h, 9-24', indications: '高血压急症、难治性高血压' },
  { id: '34', name: '盐酸利多卡因注射液', spec: '0.1g: 5ml', dose: '200mg(2支)', solvent: 'NS 40ml', speed: '15ml/h', range: '1mg/min, 1-3', indications: '室上性心律失常' },
  { id: '35', name: '注射用盐酸地尔硫卓(合贝爽) 用法1', spec: '50mg', dose: '50mg(1支)', solvent: 'NS 50ml', speed: '3.6ml/h', range: '1ug/kg/min, 1-5', indications: '不稳定型心绞痛' },
  { id: '用法2', name: '', spec: '50mg', dose: '50mg(1支)', solvent: 'NS 50ml', speed: '18ml/h', range: '5ug/kg/min, 5-15', indications: '高血压急症' },
  { id: '37', name: '肝素钠注射液', spec: '12500U: 2ml', dose: '12500U(1支)', solvent: 'NS 48ml', speed: '2ml/h', range: '500U/h, 固定走速', indications: '抗凝、预防血栓形成' },
  { id: '38', name: '盐酸奥普力农注射液(爱尔辛泰)', spec: '5mg: 5ml', dose: '15mg(3支)', solvent: 'NS/GS 35ml', speed: '2.1ml/h', range: '0.175ug/kg/min, 0.1-0.4', indications: '用于其他药物疗效不佳的急性心力衰竭的短期治疗' },
  { id: '39', name: '地西泮注射液(安定)', spec: '10mg: 2ml', dose: '10mg(1支)', solvent: 'NS 0ml (地西泮原液泵入, 溶液量仅2ml)', speed: '1ml/h', range: '5mg/h, 5-10', indications: '抗惊厥、镇静 (注：有观点认为地西泮不能用NS或GS稀释, 稀释会析出晶体, 产生浑浊)' },
  { id: '40', name: '盐酸吗啡注射液', spec: '10mg: 1ml', dose: '50mg(5支)', solvent: 'NS 45ml', speed: '1ml/h', range: '1mg/h, 1-6', indications: '镇痛、镇静' },
  { id: '41', name: '丙泊酚注射液(得普利麻)', spec: '200mg: 20ml', dose: '400mg(2支)', solvent: 'NS 10ml', speed: '2.25ml/h', range: '0.3mg/kg/h, 0.3-4.0', indications: '镇静' },
  { id: '42', name: '枸橼酸芬太尼注射液', spec: '0.1mg: 2ml', dose: '200ug(2支)', solvent: 'NS 46ml', speed: '7.5ml/h', range: '0.5ug/kg/h, 0.5-4.0', indications: '镇痛' },
  { id: '43', name: '冬眠合剂：盐酸氯丙嗪注射液25mg (1支, 规格25mg: 1ml) +盐酸异丙嗪注射液25mg (1支, 规格25mg: 1ml) +盐酸哌替啶注射液50mg (1支, 规格50mg: 2ml)。上述氯丙嗪、异丙嗪、哌替啶+NS 46ml, 1.2ml/h', spec: '', dose: '', solvent: '', speed: '', range: '', indications: '镇痛、镇静、退热。合剂中氯丙嗪对体温中枢的抑制作用，异丙嗪降低脑干网状上行激活系统的应激性，哌替啶镇痛、镇静', isFullText: true },
  { id: '44', name: '氟马西尼注射液(欣其邦)', spec: '1mg: 10ml', dose: '2mg(2支)', solvent: 'NS 30ml', speed: '2.5ml/h', range: '0.1mg/h, 固定走速', indications: '逆转苯二氮卓类药物所致的中枢铺睡' },
  { id: '45', name: '注射用维库溴铵(仙林)', spec: '4mg', dose: '40mg(10支)', solvent: 'NS 50ml', speed: '3.6ml/h', range: '0.8ug/kg/min, 0.8-1.2', indications: '肌松药, 有利于气管内插管' },
  { id: '46', name: '苯磺顺阿曲库铵注射液', spec: '10mg: 5ml', dose: '100mg(10支)', solvent: 'NS 0ml', speed: '5.4ml/h', range: '3ug/kg/min, 3-10', indications: '肌松药, 有利于气管内插管' },
  { id: '47', name: '酒石酸布托啡诺注射液(诺扬)', spec: '1mg: 1ml', dose: '4mg(4支)', solvent: 'NS 46ml', speed: '5ml/h', range: '0.4mg/h, 固定走速', indications: '镇痛' },
  { id: '48', name: '注射用奥美拉唑钠(洛赛克)', spec: '40mg', dose: '80mg(2支)', solvent: 'NS 50ml', speed: '5ml/h', range: '8mg/h, 固定走速', indications: '护胃抑酸、消化道出血' },
  { id: '49', name: '呋塞米注射液(速尿)', spec: '20mg: 2ml', dose: '40mg(2支)', solvent: 'NS 16ml (溶液量20ml)', speed: '5ml/h', range: '10mg/h, 10-40', indications: '利尿消肿、改善心脏前负荷' },
  { id: '50', name: '氨茶碱注射液', spec: '0.25g: 2ml', dose: '500mg(2支)', solvent: 'GS 46ml', speed: '2ml/h', range: '20mg/h, 固定走速', indications: '支气管哮喘、急性左心衰' },
  { id: '51', name: '胰岛素注射液', spec: '400U: 10ml', dose: '50U(1/8支)', solvent: 'NS 49ml (溶液量实为50.25ml, 视为50ml)', speed: '1ml/h', range: '1U/h, 1-? (根据血糖调整剂量)', indications: '控制血糖' },
];
